stages:
  - test
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - project: brettops/pipelines/ansible
    ref: 0.3.1
    file:
      - ansible-lint.yml
      - ansible-molecule.yml
  - project: brettops/pipelines/prettier
    ref: 0.2.0
    file:
      - prettier.yml

ansible-molecule:
  parallel:
    matrix:
      - ANSIBLE_MOLECULE_PLATFORM:
          - debian9
          - debian10
          - debian11
          - fedora37
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
