stages:
  - test
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - project: brettops/pipelines/ansible
    ref: 0.1.0
    file:
      - lint.yml
      - molecule.yml

ansible-molecule-test:
  variables:
    ANSIBLE_MOLECULE_TEST_OPTS: -p $ANSIBLE_MOLECULE_PLATFORM
  parallel:
    matrix:
      - ANSIBLE_MOLECULE_PLATFORM:
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - debian11
          - debian10
          - debian9
          - fedora37
