---
- name: Install kubectx / kubens tools
  ansible.builtin.unarchive:
    src: https://github.com/ahmetb/kubectx/releases/download/v{{ kubectx_version }}/{{ item }}_v{{ kubectx_version }}_linux_{{ ansible_architecture }}.tar.gz
    dest: "/usr/local/bin"
    exclude: ["LICENSE"]
    remote_src: "yes"
    owner: root
    group: root
    mode: "0755"
  loop:
    - kubectx
    - kubens

- name: Add completion for kubectx / kubens
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/completion/{{ item }}.bash"
    dest: "/etc/bash_completion.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - kubectx
    - kubens

- name: Link kns to kubens
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    owner: root
    group: root
    state: link
  loop:
    - src: kubens
      dest: kns
    - src: kubectx
      dest: kctx
