---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true

  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    pre_build_image: true

  - name: fedora37
    image: geerlingguy/docker-fedora37-ansible
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible
